# configuration file for dotnet-releaser
# Disable default packs - It will only publish NuGet and the Changelog
profile = "custom"
[msbuild]
project = "CodeAlta.slnx"
[github]
user = "CodeAlta"
repo = "CodeAlta"
[changelog]
# publish = false # Disable for now until release (as the changelog takes a huge amount of time to generate)
owners = ["xoofx"] # To avoid to be mentioned in the changelog
[nuget]
user = "xoofx"
trusted_publishing = true